[profile.default]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 50000

src = "src"
out = "out"
libs = ["lib"]
script = "script"
test = "test"
cache_path = "cache"
build_info = true
extra_output = ["storageLayout"]

ffi = true
ast = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
